# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'victory.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_secWindow(object):
    def setupUi(self, MainWindow,show,re,score,best):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 547, 507))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("cards/victory.jpg"))
        self.label.setObjectName("label")
        self.restart = QtWidgets.QPushButton(self.centralwidget)
        self.restart.setGeometry(QtCore.QRect(10, 540, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.restart.setFont(font)
        self.restart.setObjectName("restart")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 520, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.restart.clicked.connect(lambda :self.restart2(show,re,MainWindow))

        self.retranslateUi(MainWindow,score,best)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow,score,best):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.restart.setText(_translate("MainWindow", "Restart"))
        self.label_2.setText(_translate("MainWindow", f"Score:{score}\nBest:{best}"))
    def restart2(self,show,re,win):
        show.show()
        re()
        win.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_secWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
